export const mockColleges = [
  {
    id: '1',
    name: 'Adhi College of Engineering and Technology',
    type: 'Private',
    location_city: 'Chennai',
    location_state: 'Tamil Nadu',
    fees_min: 140000,
    fees_max: 160000,
    description: 'Premier engineering college with state-of-the-art facilities and excellent placement records.',
    application_deadline: '2025-04-30',
    courses: ['B.Tech in AI', 'B.Tech in CSE', 'B.Tech in ECE'],
  },
  {
    id: '2',
    name: 'Sri Krishna College of Technology',
    type: 'Private',
    location_city: 'Coimbatore',
    location_state: 'Tamil Nadu',
    fees_min: 120000,
    fees_max: 150000,
    description: 'Autonomous institution known for innovation and entrepreneurship development.',
    application_deadline: '2025-05-15',
    courses: ['B.Tech in CSE', 'B.Tech in Mechanical', 'B.Tech in Civil'],
  },
  {
    id: '3',
    name: 'PSG College of Arts & Science',
    type: 'Autonomous',
    location_city: 'Coimbatore',
    location_state: 'Tamil Nadu',
    fees_min: 50000,
    fees_max: 80000,
    description: 'Renowned for quality education in science and arts with affordable fees.',
    application_deadline: '2025-06-01',
    courses: ['B.Sc Computer Science', 'B.Com', 'BCA'],
  },
  {
    id: '4',
    name: 'Madras Christian College',
    type: 'Autonomous',
    location_city: 'Chennai',
    location_state: 'Tamil Nadu',
    fees_min: 30000,
    fees_max: 60000,
    description: 'Historic institution offering diverse undergraduate and postgraduate programs.',
    application_deadline: '2025-05-20',
    courses: ['B.A English', 'B.Sc Physics', 'B.Com'],
  },
  {
    id: '5',
    name: 'VIT University',
    type: 'Private',
    location_city: 'Vellore',
    location_state: 'Tamil Nadu',
    fees_min: 195000,
    fees_max: 220000,
    description: 'Top-ranked university with international collaborations and excellent infrastructure.',
    application_deadline: '2025-04-15',
    courses: ['B.Tech CSE', 'B.Tech AI & ML', 'B.Tech Robotics'],
  },
];

export const mockCourses = [
  {
    id: '1',
    name: 'Computer Science & Engineering',
    category: 'Engineering',
    duration_years: 4,
    description: 'Learn programming, algorithms, software development, and emerging technologies.',
    career_options: ['Software Developer', 'Data Scientist', 'AI Engineer', 'Cloud Architect'],
    average_salary_min: 400000,
    average_salary_max: 1200000,
  },
  {
    id: '2',
    name: 'Mechanical Engineering',
    category: 'Engineering',
    duration_years: 4,
    description: 'Study design, manufacturing, and maintenance of mechanical systems.',
    career_options: ['Mechanical Engineer', 'Production Manager', 'Design Engineer', 'Quality Control'],
    average_salary_min: 350000,
    average_salary_max: 800000,
  },
  {
    id: '3',
    name: 'Bachelor of Commerce',
    category: 'Commerce',
    duration_years: 3,
    description: 'Build expertise in accounting, finance, taxation, and business management.',
    career_options: ['Chartered Accountant', 'Financial Analyst', 'Tax Consultant', 'Business Analyst'],
    average_salary_min: 300000,
    average_salary_max: 700000,
  },
  {
    id: '4',
    name: 'BSc Computer Science',
    category: 'Science',
    duration_years: 3,
    description: 'Comprehensive study of computer fundamentals, programming, and applications.',
    career_options: ['Software Developer', 'System Administrator', 'Web Developer', 'Tech Support'],
    average_salary_min: 350000,
    average_salary_max: 900000,
  },
  {
    id: '5',
    name: 'MBBS',
    category: 'Medical',
    duration_years: 5.5,
    description: 'Professional degree to become a medical doctor with clinical training.',
    career_options: ['Doctor', 'Surgeon', 'Specialist', 'Medical Researcher'],
    average_salary_min: 600000,
    average_salary_max: 2000000,
  },
];

export const mockApplications = [
  {
    id: 'APP11234',
    college_name: 'Adhi College of Engineering',
    course_name: 'B.Tech Computer Science',
    status: 'Under Review',
    applied_at: '2025-09-15',
    next_steps: 'Please submit your 12th standard mark sheets by October 10, 2025',
    documents_submitted: {
      marksheet: true,
      id_proof: true,
      photo: false,
      transfer_certificate: false,
    },
  },
  {
    id: 'APP11235',
    college_name: 'VIT University',
    course_name: 'B.Tech AI & ML',
    status: 'Shortlisted',
    applied_at: '2025-09-10',
    next_steps: 'Interview scheduled for October 15, 2025 at 10:00 AM',
    documents_submitted: {
      marksheet: true,
      id_proof: true,
      photo: true,
      transfer_certificate: true,
    },
  },
];

export const mockCounselors = [
  { name: 'Dr. Aisha Khan', available: true },
  { name: 'Prof. Rajesh Kumar', available: true },
  { name: 'Ms. Priya Sharma', available: true },
];

export const mockTimeSlots = [
  { date: '2025-10-12', time: '10:00 AM' },
  { date: '2025-10-12', time: '02:00 PM' },
  { date: '2025-10-12', time: '04:00 PM' },
  { date: '2025-10-13', time: '11:00 AM' },
  { date: '2025-10-13', time: '03:00 PM' },
  { date: '2025-10-14', time: '09:00 AM' },
  { date: '2025-10-14', time: '02:00 PM' },
  { date: '2025-10-15', time: '10:30 AM' },
];
